# Generated by Django 4.0.1 on 2022-01-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('m_name', models.TextField()),
                ('m_loc', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
    ]
