# Generated by Django 4.0.1 on 2022-01-27 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_boardmember_id'),
        ('review', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boardMember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.boardmember'),
        ),
        migrations.AlterField(
            model_name='post',
            name='m_loc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='m_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
