# Generated by Django 4.0.1 on 2022-01-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_post_boardmember_alter_post_m_loc_alter_post_m_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='boardMember',
        ),
    ]
