# Generated by Django 4.0.1 on 2022-01-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_post_boardmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
