# Generated by Django 4.0.1 on 2022-01-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
