# Generated by Django 4.0.1 on 2022-01-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_boardmember_id'),
        ('review', '0008_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_column='author', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.boardmember'),
        ),
    ]
