# Generated by Django 3.2.5 on 2022-01-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('loc', models.TextField(null=True)),
                ('height', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('routeimglink', models.TextField(null=True)),
                ('detail', models.TextField(null=True)),
                ('tourism', models.TextField(null=True)),
                ('tourismimglink', models.TextField(null=True)),
            ],
            options={
                'db_table': 'mountain',
                'managed': False,
            },
        ),
    ]
