# Generated by Django 2.2.5 on 2022-01-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountain',
            options={'managed': False},
        ),
    ]
