# Generated by Django 3.2.5 on 2022-01-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountainRoute',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('link', models.TextField(null=True)),
            ],
            options={
                'db_table': 'mountain_route',
                'managed': False,
            },
        ),
    ]
