# Generated by Django 2.2.5 on 2022-01-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20220123_0003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mountain',
            table='info_mountain',
        ),
    ]
