# Generated by Django 2.2.5 on 2022-01-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20220123_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mountain',
        ),
    ]
