# Generated by Django 2.2.5 on 2022-01-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0004_delete_mountain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain_id', models.IntegerField()),
                ('name', models.TextField()),
                ('loc', models.TextField()),
                ('height', models.TextField()),
                ('overview', models.TextField()),
                ('routeimglink', models.TextField()),
                ('detail', models.TextField()),
                ('tourism', models.TextField()),
                ('tourismimglink', models.TextField()),
            ],
            options={
                'db_table': 'info_mountain',
                'managed': False,
            },
        ),
    ]
