# Generated by Django 2.2.5 on 2022-01-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_mountain'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mountain',
            table='mountain',
        ),
    ]
