# Generated by Django 2.2.5 on 2022-01-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20220124_1000'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mountain',
            table='info_mountain',
        ),
    ]
